spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  exchange-name: smart-engineer-exchange
  routing-key: smart-engineer-routing-key
  queue-name: smart-engineer-queue
