spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  queue:
    name: smart-engineer-queue
    json-name: smart-engineer-json-queue
  exchange:
    name: smart-engineer-exchange
  routing:
    key: smart-engineer-routing-key
    json-key: smart-engineer-routing-json-key
